// <auto-generated />
using System;
using MetadataService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetadataService.Infrastructure.Migrations
{
    [DbContext(typeof(MetadataContext))]
    [Migration("20190205134501_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MetadataService.Infrastructure.Entities.AuthorizationCookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cookie");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("Role");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.ToTable("AuthorizationCookies");
                });

            modelBuilder.Entity("MetadataService.Infrastructure.Entities.CmsContent", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description");

                    b.Property<int>("ThemeId");

                    b.Property<string>("Title");

                    b.Property<int?>("VideoInfoId");

                    b.HasKey("Id");

                    b.HasIndex("VideoInfoId");

                    b.ToTable("CmsContents");
                });

            modelBuilder.Entity("MetadataService.Infrastructure.Entities.Theme", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("MetadataService.Infrastructure.Entities.VideoInfo", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("State");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("VideoInfos");
                });

            modelBuilder.Entity("MetadataService.Infrastructure.Entities.CmsContent", b =>
                {
                    b.HasOne("MetadataService.Infrastructure.Entities.VideoInfo", "VideoInfo")
                        .WithMany()
                        .HasForeignKey("VideoInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
